/**
 * Tracking snippet generation. The snippet is intentionally dependency-free
 * and versioned by the serving app: it loads the collector script with the
 * site key and lets the collector do the work.
 */

/** Registrable host[:port] — the only shape we will interpolate into JS. */
const HOST_PATTERN = /^[A-Za-z0-9](?:[A-Za-z0-9.-]*[A-Za-z0-9])?(?::\d{1,5})?$/

const SAFE_FALLBACK_HOST = 'localhost:3000'

/** Escape a value for inclusion inside a single-quoted JS string literal. */
function escapeJsString(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
}

export function buildSnippet(siteKey: string, collectorUrl: string): string {
  // siteKey and collectorUrl are server-controlled (key is generated by
  // generateSiteKey, URL is derived from the validated request origin), so
  // no user-supplied content is interpolated into script context — but both
  // are still validated/escaped as defence in depth.
  if (!/^px_[0-9a-f]{16}$/.test(siteKey)) {
    throw new Error(`Invalid site key: ${siteKey.slice(0, 24)}`)
  }
  const url = escapeJsString(collectorUrl)
  const key = escapeJsString(siteKey)
  // `document` is passed as the OBJECT (not a string literal): the IIFE calls
  // i.createElement on it. Round-5 regression-tested in node:vm — a quoted
  // 'document' throws before the collector ever loads (R5-C1).
  // R15-F6: the live indents the loader body two spaces (its docs-page
  // sample uses the same convention).
  return `<script>
  (function(p,i,x,e,l){p._pxq=p._pxq||[];
  var s=i.createElement('script');s.async=1;
  s.src='${url}';
  s.setAttribute('data-site',e);
  i.head.appendChild(s);})(window,document,'px','${key}');
</script>`
}

/** Absolute collector URL for the current request. */
export function collectorUrlFromHeaders(host: string, proto?: string | null): string {
  const protocol = proto === 'http' || proto === 'https' ? proto : 'https'
  // x-forwarded-host is attacker-controllable when a proxy forwards it from
  // the client. Only a registrable host[:port] is ever interpolated into the
  // snippet; anything else falls back to a safe default.
  const safeHost = HOST_PATTERN.test(host) ? host : SAFE_FALLBACK_HOST
  return `${protocol}://${safeHost}/pixel.js`
}
