/**
 * Tracking snippet generation. The snippet is intentionally dependency-free
 * and versioned by the serving app: it loads the collector script with the
 * site key and lets the collector do the work.
 */

/** Registrable host[:port] — the only shape we will interpolate into JS. */
const HOST_PATTERN = /^[A-Za-z0-9](?:[A-Za-z0-9.-]*[A-Za-z0-9])?(?::\d{1,5})?$/

const SAFE_FALLBACK_HOST = 'localhost:3000'

/** Escape a value for inclusion inside a single-quoted JS string literal. */
function escapeJsString(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
}

export function buildSnippet(siteKey: string, collectorUrl: string): string {
  // siteKey and collectorUrl are server-controlled (key is generated by
  // generateSiteKey, URL is derived from the validated request origin), so
  // no user-supplied content is interpolated into script context — but both
  // are still validated/escaped as defence in depth.
  if (!/^px_[0-9a-f]{16}$/.test(siteKey)) {
    throw new Error(`Invalid site key: ${siteKey.slice(0, 24)}`)
  }
  const url = escapeJsString(collectorUrl)
  const key = escapeJsString(siteKey)
  // `document` is passed as the OBJECT (not a string literal): the IIFE calls
  // i.createElement on it. Round-5 regression-tested in node:vm — a quoted
  // 'document' throws before the collector ever loads (R5-C1).
  // R15-F6: the live indents the loader body two spaces (its docs-page
  // sample uses the same convention).
  return `<script>
  (function(p,i,x,e,l){p._pxq=p._pxq||[];
  var s=i.createElement('script');s.async=1;
  s.src='${url}';
  s.setAttribute('data-site',e);
  i.head.appendChild(s);})(window,document,'px','${key}');
</script>`
}

/** Absolute collector URL for the current request. */
export function collectorUrlFromHeaders(host: string, proto?: string | null): string {
  const protocol = proto === 'http' || proto === 'https' ? proto : 'https'
  // x-forwarded-host is attacker-controllable when a proxy forwards it from
  // the client. Only a registrable host[:port] is ever interpolated into the
  // snippet; anything else falls back to a safe default.
  const safeHost = HOST_PATTERN.test(host) ? host : SAFE_FALLBACK_HOST
  return `${protocol}://${safeHost}/pixel.js`
}

/** R24 F2: platforms whose install tab ships a per-tab snippet pre. */
export type PlatformId = 'wordpress' | 'shopify' | 'gtm'

/**
 * R24 F2: the live's per-platform snippet pre, decoded from its install
 * page (all four tabs captured verbatim, R24 plan 9th probe generation).
 * WordPress/Shopify prepend a two-line HTML comment header to the standard
 * snippet; the GTM variant additionally inlines the site key as the
 * setAttribute literal (its bundle's own quirk — `data-site` receives the
 * raw key, not the `e` parameter). Key/URL validation mirrors buildSnippet
 * (both are server-controlled, but defence in depth).
 */
const PLATFORM_HEADERS: Record<PlatformId, string> = {
  wordpress:
    `<!-- Add to your theme's header.php or use a plugin like "Insert Headers and Footers" -->\n` +
    '<!-- Paste this before the closing </head> tag -->',
  shopify:
    '<!-- In Shopify Admin → Online Store → Themes → Edit Code -->\n' +
    '<!-- Open theme.liquid and paste before </head> -->',
  gtm: '<!-- In GTM, create a Custom HTML tag -->\n<!-- Trigger: All Pages -->',
}

export function buildPlatformSnippet(
  platform: PlatformId,
  siteKey: string,
  collectorUrl: string,
): string {
  if (!/^px_[0-9a-f]{16}$/.test(siteKey)) {
    throw new Error(`Invalid site key: ${siteKey.slice(0, 24)}`)
  }
  const header = `${PLATFORM_HEADERS[platform]}\n`
  if (platform === 'gtm') {
    // The GTM variant: the setAttribute argument is the LITERAL key.
    const url = escapeJsString(collectorUrl)
    const key = escapeJsString(siteKey)
    return `${header}<script>
  (function(p,i,x,e,l){p._pxq=p._pxq||[];
  var s=i.createElement('script');s.async=1;
  s.src='${url}';
  s.setAttribute('data-site','${key}');
  i.head.appendChild(s);})(window,document,'px','${key}');
</script>`
  }
  return header + buildSnippet(siteKey, collectorUrl)
}
