/**
 * Tracking snippet generation. The snippet is intentionally dependency-free
 * and versioned by the serving app: it loads the collector script with the
 * site key and lets the collector do the work.
 */

export function buildSnippet(siteKey: string, collectorUrl: string): string {
  // siteKey and collectorUrl are server-controlled (key is generated by
  // generateSiteKey, URL is derived from the request origin), so no
  // user-supplied content is interpolated into script context.
  return `<script>
(function(p,i,x,e,l){p._pxq=p._pxq||[];
var s=i.createElement('script');s.async=1;
s.src='${collectorUrl}';
s.setAttribute('data-site',e);
i.head.appendChild(s)})(window,'document','px','${siteKey}');
</script>`
}

/** Absolute collector URL for the current request. */
export function collectorUrlFromHeaders(host: string, proto?: string | null): string {
  const protocol = proto === 'http' || proto === 'https' ? proto : 'https'
  return `${protocol}://${host}/pixel.js`
}
